Repository Holmusk/postgresql-simple-named, pull requests merged in 2019-07, with the labels that each got.

#1 Initial implementation
  .gitignore
  .travis.yml
  postgresql-simple-named.cabal
  src/PgNamed.hs
  src/PostgresqlSimpleNamed.hs
  stack.yaml
Labels: enhancement

#4 [#3] Implement query functions
  postgresql-simple-named.cabal
  src/PgNamed.hs
Labels: enhancement

#6 [#2] Add doctest
  postgresql-simple-named.cabal
  src/PgNamed.hs
  test/Doctest.hs
Labels: tests

#7 [#2] Add query tests for named parameters
  .travis.yml
  README.md
  postgresql-simple-named.cabal
  test/Spec.hs
Labels: tests

#9 [#8] Use Connection instead of Pool
  postgresql-simple-named.cabal
  src/PgNamed.hs
  test/Spec.hs
Labels: enhancement

#11 [#10] Lower fixity of =? operator
  src/PgNamed.hs
Labels: enhancement

#13 [#12] Support latest 2 GHC versions
  .travis.yml
  postgresql-simple-named.cabal
Labels: enhancement

#14 [#5] Write some README
  README.md
  postgresql-simple-named.cabal
  src/PgNamed.hs
Labels: documentation
